title: Unicode Proposals
description: Proposals for new characters to encode and canonic character sequences to register
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
include: references

gems:
  - jekyll-mentions
